services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: salma
      POSTGRES_PASSWORD: spacex123
      POSTGRES_DB: spacexdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: